version: '3'

networks:
  rede-desafio2:
    driver: bridge

services:

  db:
    image: mysql:5.7 
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - rede-desafio2
    tty: true

  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - rede-desafio2
    command: node index.js
    depends_on:
      - db

  proxy:
    build: ./nginx
    image: nginx
    container_name: proxy-reverso
    networks:
      - rede-desafio2
    ports:
      - 8080:80
    depends_on:
      - app 
